---
types:
  - name: "Blackhead"
    definition: "The type of acne that appear as small, dark spots on the skin."
    causes: "Blackheads form due to clogged pores from excess oil and dead skin cells."
    prevention: "Gentle, non-comedogenic cleansing, regular exfoliation, and oil-free moisturizers are key for maintaining clear, healthy skin."
    treatment: "OTC treatments, professional extractions, and exfoliating treatments can help manage blackheads, while severe cases may require prescription medications. Consistent skincare is key to preventing blackhead worsening."
  - name: "Nodule"
    definition: "The type of acne lesion that appear as hard, painful bumps under the skin's surface."
    causes: "Nodules develop from deep pore blockages that trigger severe inflammation under the skin."
    prevention: "Gentle cleansing, use of oil-controlling/exfoliating ingredients, avoiding picking, managing stress, and consulting a dermatologist are key for controlling acne."
    treatment: "Combination of topical, oral, and in-office treatments, plus consistent gentle skincare, is key to managing nodular acne and preventing scarring."
  - name: "Papule"
    definition: "The type of acne lesion that appear as small, solid, elevated bumps on the skin."
    causes: "Papules are caused by clogged pores that trigger inflammation, leading to raised, red bumps."
    prevention: "Gentle cleansing, use of exfoliating ingredients, avoiding over-washing, managing stress, and consulting a dermatologist are key for acne management."
    treatment: "Comprehensive treatment approach including topicals, orals, in-office procedures, and gentle skincare is key for managing papular acne and preventing scarring."
  - name: "Pustule"
    definition: "The type of acne lesion that appear as small, pus-filled bumps on the skin."
    causes: "Pustules develop from clogged pores filled with pus and bacteria, causing inflamed bumps."
    prevention: "Key acne management steps include gentle cleansing, use of exfoliating ingredients, avoiding picking, managing stress, and consulting a dermatologist."
    treatment: "Comprehensive treatment with topicals, orals, in-office procedures, and gentle skincare is key for managing pustular acne and preventing scarring."
  - name: "Whitehead"
    definition: "The type of acne lesion that appear as small, white or yellowish bumps on the skin."
    causes: "Whiteheads form from subsurface pore blockages of oil, dead skin, and bacteria."
    prevention: "Gentle cleansing, use of exfoliating ingredients, avoiding over-washing, managing stress, and consulting a dermatologist are key acne management steps."
    treatment: "Topical treatments, professional extractions, and gentle skincare are effective for managing whiteheads, but home extraction should be avoided to prevent irritation and scarring."
...